spring:
  profiles: local
  kafka:
    consumer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-deserializer: org.apache.kafka.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.serialization.StringDeserializer
      group-id: library-events-listener-group
    listener:
      ack-mode: MANUAL
      concurrency: 3
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true

---
server:
  port: 8081